###############################################################################
# APEL scaling: persist selected execute-node attributes into job history
###############################################################################
SYSTEM_JOB_MACHINE_ATTRS = $(SYSTEM_JOB_MACHINE_ATTRS), ACCOUNTING_SCALE_FACTOR
SYSTEM_JOB_MACHINE_ATTRS_HISTORY_LENGTH = 1
