#!/bin/bash
export PATH=/cvmfs/oasis.opensciencegrid.org/mis/singularity/bin:$PATH

if [ "$1" == "--version" ]
then
  singularity --version
  exit 0
fi


# user might not be set (e.g. when not using getenv in job config)
USER=`whoami`
export USER

# try to figure out the HOME for the user - default to condor workdir
if [ -d "/users/$USER" ]
then
  HOME="/users/$USER"
elif [ -d "/usersc/$USER" ]
then
  HOME="/usersc/$USER"
else
  HOME="$TMPDIR"
fi
export HOME

# make sure SINGULARITY_HOME is set to a correct value (e.g a folder owned by the user)
export SINGULARITY_HOME=$HOME
export HOSTNAME=`hostname -f`

echo "Executing singularity $1 --home $HOME ${@:2}"
singularity $1 --home $HOME ${@:2}
