###############################################################################
# Local site APEL settings (site-owned override)
###############################################################################
APEL_OUTPUT_DIR = /var/lib/condor-ce/apel/
USE_VOMS_ATTRIBUTES = True
APEL_SCALING_ATTR = MachineAttrACCOUNTING_SCALE_FACTOR0
APEL_USE_WLCG_GROUPS = True
