---
classes:
  - profile::cvmfs
  - profile::cephfs
  - packages::manage
  - podman
  - profile::htcondor
  - profile::apptainer
  - profile::heposlibs
  - profile::nfs_mounts

profile::htcondor::role: "execute"

podman::enable_api_socket: true
profile::monitored::use_prometheus: false

profile::users::shell: '/sbin/nologin'

cvmfs::cvmfs_cache_base: '/var/cache/cvmfs'

profile::users::groups:
  condor:
    gid: '9618'

profile::users::users:
  condor:
    uid: '9618'
    gid: '9618'
    home: '/var/lib/condor'
    shell: '/sbin/nologin'
    comment: 'condor superuser'
    group: condor

profile::cephfs::keys:
  - condor
  - dice-user

profile::cephfs::mounts:
  '/condor':
    device: condor@.dicefs=/condor
  '/dice':
    device: dice-user@.dicefs=/dice
  '/xrootd':
    device: dice-user@.dicefs=/xrootd

profile::nfs_mounts::mounts:
  '/shared/scratch':
    path: /exports/scratch
    read_only: false
  '/users':
    path: /exports/users
    read_only: true
  '/software':
    path: /exports/software
    read_only: true
