cvmfs::mount_method: 'mount'

classes:
  - profile::cvmfs
  - podman
  - profile::cephfs
  - profile::hdfs
  - packages::manage

packages::install:
  - nano
  - wget

cvmfs::cvmfs_cache_base: '/var/cache/cvmfs'

profile::users::groups:
  condor:
    gid: '9618'

profile::users::users:
  condor:
    uid: '9618'
    gid: '9618'
    home: '/var/spool/condor'
    shell: '/sbin/nologin'
    comment: 'condor superuser'
    group: condor

profile::cephfs::keys:
  - dice-user

profile::cephfs::mounts:
  '/condor':
    device: dice-user@.dicefs=/condor
  '/dice':
    device: dice-user@.dicefs=/dice
  '/xrootd':
    device: dice-user@.dicefs=/xrootd
