cvmfs::mount_method: 'mount'

classes:
  - podman
  - profile::cephfs
  - packages::manage
  - profile::htcondor
  - profile::users::poolaccounts

profile::htcondor::role: "central-manager"

packages::install:
  - nano
  - wget

profile::cephfs::keys:
  - condor

profile::cephfs::mounts:
  '/condor':
    device: condor@.dicefs=/condor

firewalld::ports:
  "Open standard condor ports":
    ensure: present
    zone: public
    port: 9618
    protocol: 'tcp'
