classes:
  - profile::firewalld
  - profile::cephfs

site::node_info::users: pool_accounts

firewalld::ports:
  "Open port 9618 for condor":
    ensure: present
    zone: public
    port: 9618
    protocol: 'tcp'

firewalld::services:
  "Allow access to HTTP service on port 80 for CEView (internal only)":
    service: http
    zone: public
    ensure: present

profile::cephfs::keys:
  - dice-user

profile::cephfs::mounts:
  '/condor':
    device: dice-user@.dicefs=/condor
  '/dice':
    device: dice-user@.dicefs=/dice
  '/xrootd':
    device: dice-user@.dicefs=/xrootd
