cvmfs::mount_method: 'mount'

classes:
  - profile::cvmfs
  - podman
  - profile::cephfs

packages:
  - centos-release-ceph-reef
  - ceph

cvmfs::cvmfs_cache_base: '/var/cache/cvmfs'

profile::users::groups:
  condor:
    gid: '9618'

profile::users::users:
  condor:
    uid: '9618'
    gid: '9618'
    home: '/var/spool/condor'
    shell: '/sbin/nologin'
    comment: 'condor superuser'
    group: condor

profile::cephfs::keys:
  - condor
  - dice-user
  - xrootd-user
profile::cephfs::mounts:
  condor:
    name: '/condor'
    fstype: 'cephfs'
    device: condor@.dicefs=/condor
  dice:
    name: '/dice'
    fstype: 'cephfs'
    device: dice-user@.dicefs=/dice
  xrootd:
    name: '/xrootd'
    fstype: 'cephfs'
    device: xrootd-user@.dicefs=/xrootd
