classes:
  - profile::cvmfs
  - podman
  - profile::cephfs
  - profile::hdfs
  - packages::manage
  - profile::htcondor
  - profile::apptainer
  - profile::heposlibs
  - profile::nfs_mounts

profile::htcondor::role: "submit"
profile::htcondor::submit::periodic_remove_requirements:
  RemoveDefaultJobWallTime: "RemoteWallClockTime > 8 * 30 * 24 * 60 * 60"
  RemoveDefaultJobCpuTime: "RemoteSysCpu + RemoteUserCpu > 30 * 24 * 60 * 60"
  RemoveMemoryUsage: "ResidentSetSize_RAW > 1000 * RequestMemory"
  RemoveHeldJobs: "(JobStatus==5 && (CurrentTime - EnteredCurrentStatus) > 30 * 60)"
  RemoveMultipleRunJobs: "JobRunCount > 10"

packages::install:
  - nano
  - wget

cvmfs::cvmfs_cache_base: '/var/cache/cvmfs'

profile::users::groups:
  condor:
    gid: '9618'

profile::users::users:
  condor:
    uid: '9618'
    gid: '9618'
    home: '/var/lib/condor'
    shell: '/sbin/nologin'
    comment: 'condor superuser'
    group: condor

profile::cephfs::keys:
  - dice-user

profile::cephfs::mounts:
  '/condor':
    device: dice-user@.dicefs=/condor
  '/dice':
    device: dice-user@.dicefs=/dice
  '/xrootd':
    device: dice-user@.dicefs=/xrootd

profile::nfs_mounts::mounts:
  '/shared/scratch':
    path: /exports/scratch
    read_only: false
    group: users
  '/users':
    path: /exports/users
    read_only: false
  '/software':
    path: /exports/software
    read_only: false
    group: users
  '/opt/astro':
    server: echidna.star.bris.ac.uk
    path: /data/echidna1
    read_only: true
    group: dice-astro

firewalld::ports:
  "Open standard condor ports":
    ensure: present
    zone: public
    port: 9618
    protocol: 'tcp'
