---
classes:
  # - role::htcondor_worker
  - 'profile::cvmfs'
  - 'profile::arc_env'
  - 'profile::voenv'
  - profile::cgroups
  - profile::cephfs

site::node_info:
  firewall: worker_node

htcondor::is_worker: true
htcondor::enable_cgroup: true
htcondor::use_pid_namespaces: true

htcondor::enable_healthcheck: true
htcondor::healthcheck_path: /etc/condor/healthcheck_workernode
htcondor::healthcheck_period: "10m"
htcondor::healthcheck_script: "puppet:///modules/role/etc/condor/healthcheck_workernode"

htcondor::use_singularity: true
htcondor::singularity_image_expr: 'TARGET.SingularityImage'
htcondor::force_singularity_jobs: '!isUndefined(TARGET.SingularityImage)'
htcondor::singularity_target_dir: '/srv'
htcondor::starter_job_environment:
  SINGULARITY_HOME: '/srv'
htcondor::singularity_path: '/etc/condor/singularity_wrapper'
htcondor::singularity_bind_paths:
  - /hdfs
  - /cvmfs
  - /software
  - /users
  - /usersc
  - /condor/condor
  - /opt

singularity::package_ensure: absent
singularity::package_name: singularity-runtime
singularity::manage_epel: false
# singularity::config_path: /etc/singularity/singularity.conf
# singularity::config_template: singularity/singularity.conf.erb
singularity::allow_setuid: 'yes'
singularity::max_loop_devices: 256
singularity::allow_pid_ns: 'yes'
singularity::config_passwd: 'yes'
singularity::config_group: 'yes'
singularity::config_resolv_conf: 'yes'
singularity::mount_proc: 'yes'
singularity::mount_sys: 'yes'
singularity::mount_dev: 'yes'
singularity::mount_devpts: 'yes'
singularity::mount_home: 'yes'
singularity::mount_tmp: 'yes'
singularity::mount_hostfs: 'no'
singularity::bind_paths:
  - /etc/localtime
  - /etc/hosts
  - /cvmfs
  - /hdfs
  - /users
  - /usersc
  - /software
  - /condor/condor
  - /usr/libexec/condor
  - /etc/hadoop
  - /opt/cloudera
singularity::user_bind_control: 'yes'
singularity::enable_overlay: 'try'
singularity::mount_slave: 'yes'
singularity::sessiondir_max_size: 16
#singularity::limit_container_owners: undef
#singularity::limit_container_paths: undef
singularity::allow_containers:
  squashfs: 'yes'
  extfs: 'yes'
  dir: 'yes'

profile::cephfs::keys:
  - dice-user

profile::cephfs::mounts:
  '/dice':
    device: dice-user@.dicefs=/dice
  '/xrootd':
    device: dice-user@.dicefs=/xrootd
