
classes:
  - profile::htcondor_ce

htcondor_ce::condor_view_hosts: ['lcgce02.phy.bris.ac.uk']
htcondor_ce::job_routes_template: 'htcondor_ce/job_routes.conf.erb'
htcondor_ce::uid_domain: $::domain
htcondor_ce::use_static_shadow: false
htcondor_ce::ce_version: present
htcondor_ce::lrms: 'condor'
htcondor_ce::lrms_version: present
htcondor_ce::gsi_regex: '^\/DC\=ch\/DC\=cern\/OU\=computers\/CN\=(host\/)?([A-Za-z0-9.\-]*)$'
htcondor_ce::manage_service: true
htcondor_ce::gsi_backend: 'argus'
htcondor_ce::argus_resourceid: 'http://authz-interop.org/xacml/resource/resource-type/arc'
htcondor_ce::install_bdii: true
htcondor_ce::benchmark_result: '09.99-HEP-SPEC06'
htcondor_ce::execution_env_cores: 8
htcondor_ce::election_type: 'leader'
htcondor_ce::election_hosts: $::fqdn
htcondor_ce::apel_scaling_attr: MachineAttrACCOUNTING_SCALE_FACTOR0