
classes:
  - profile::htcondor_ce

htcondor_ce::condor_view_hosts: ['lcgce02.phy.bris.ac.uk']
htcondor_ce::job_routes_template: 'htcondor_ce/job_routes.conf.erb'
htcondor_ce::uid_domain: $::domain
htcondor_ce::use_static_shadow: false
htcondor_ce::ce_version: present
htcondor_ce::lrms: 'condor'
htcondor_ce::lrms_version: present
htcondor_ce::gsi_regex: '^\/DC\=ch\/DC\=cern\/OU\=computers\/CN\=(host\/)?([A-Za-z0-9.\-]*)$'
htcondor_ce::manage_service: true
htcondor_ce::gsi_backend: 'argus'
htcondor_ce::hostDN: "/C=UK/O=eScience/OU=Bristol/L=IS/CN=lcgce02.phy.bris.ac.uk"
htcondor_ce::argus_resourceid: 'http://authz-interop.org/xacml/resource/resource-type/arc'
htcondor_ce::install_bdii: true
htcondor_ce::install_apel: true
htcondor_ce::benchmark_result: "[ specfp2000 = 3150; hep_spec06 = 10.0; specint2000 = 2625 ]"
htcondor_ce::hepspec06: 10.0
htcondor_ce::execution_env_cores: 8
htcondor_ce::election_type: 'leader'
htcondor_ce::election_hosts: 'lcgce02.phy.bris.ac.uk'
htcondor_ce::apel_scaling_attr: ACCOUNTING_SCALE_FACTOR
htcondor_ce::apel_use_test_queue: false

# instead of using JOB_ROUTER_DEFAULTS, make every route explicit for debugging
htcondor_ce::job_routes_base_settings:
    TargetUniverse: 5
    eval_set_AccountingGroup: 'strcat("group_u_", x509userproxyvoname, ".", Owner)'
    delete_SUBMIT_Iwd: true
    set_WantIOProxy: true
    set_default_maxMemory: 3000
    set_Requirements: 'TARGET.OpSysAndVer == "CentOS7"'
htcondor_ce::job_routes:
  dice_atlas_centos7:
    Requirements: '(x509UserProxyVOName == "atlas");'
  dice_cms_centos7:
    Requirements: '(x509UserProxyVOName == "cms");'
  dice_dune_centos7:
    Requirements: '(x509UserProxyVOName == "dune");'
  dice_gridpp_centos7:
    Requirements: '(x509UserProxyVOName == "gridpp");'
  dice_ilc_centos7:
    Requirements: '(x509UserProxyVOName == "ilc");'
  dice_lhcb_centos7:
    Requirements: '(x509UserProxyVOName == "lhcb");'
  dice_lsst_centos7:
    Requirements: '(x509UserProxyVOName == "lsst");'
  dice_lz_centos7:
    Requirements: '(x509UserProxyVOName == "lz");'
  dice_ops_centos7:
    Requirements: '(x509UserProxyVOName == "ops");'
  dice_mu3e_centos7:
    Requirements: '(x509UserProxyVOName == "mu3e");'
  dice_other_centos7:
    Requirements: '(x509UserProxyVOName =!= "atlas") && (x509UserProxyVOName =!= "cms") && (x509UserProxyVOName =!= "dune") && (x509UserProxyVOName =!= "gridpp") && (x509UserProxyVOName =!= "ilc") && (x509UserProxyVOName =!= "lhcb") && (x509UserProxyVOName =!= "lsst") && (x509UserProxyVOName =!= "lz") && (x509UserProxyVOName =!= "ops") && (x509UserProxyVOName =!= "mu3e");'
