classes:
  - profile::cephfs
  - packages::manage
  - podman
  - profile::firewalld
  - profile::nfs_mounts

podman::compose_pkg_ensure: 'installed'

profile::users::shell: '/sbin/nologin'

profile::users::groups:
  condor:
    gid: '9618'

profile::users::users:
  condor:
    uid: '9618'
    gid: '9618'
    home: '/var/lib/condor'
    shell: '/sbin/nologin'
    comment: 'condor superuser'
    group: condor


firewalld::ports:
  "Open standard condor ports":
    ensure: present
    zone: public
    port: 9618
    protocol: 'tcp'
  "Open condor monitoring port":
    ensure: present
    zone: public
    port: 19618
    protocol: 'tcp'
  

firewalld::services:
  "Allow access to HTTP service on port 80 for CEView (internal only)":
    service: http
    zone: public
    ensure: present

profile::cephfs::keys:
  - condor
  - dice-user

profile::cephfs::mounts:
  '/condor':
    device: condor@.dicefs=/condor
  '/dice':
    device: dice-user@.dicefs=/dice
  '/xrootd':
    device: dice-user@.dicefs=/xrootd


profile::nfs_mounts::mounts:
  '/shared/scratch':
    path: /exports/scratch
    read_only: false
    group: users
  '/users':
    path: /exports/users
    read_only: true
  '/software':
    path: /exports/software
    read_only: true
    group: users
  '/opt/astro':
    server: echidna.star.bris.ac.uk
    path: /data/echidna1
    read_only: true
    group: dice-astro
