---
# Profiles
# ======================================================================

classes:
  - profile::nfs::server

profile::dice_scripts::manage_scripts: true
profile::dice_scripts::manage_cron: true
# Data
# ======================================================================
