---
# Profiles
# ======================================================================

classes:
  - profile::nfs::server

# Data
# ======================================================================
