---
classes:
  - profile::firewalld
  - profile::squid

firewalld::ports:
  "Open port  3128 for squid":
    ensure: present
    zone: public
    port: 3128
    protocol: 'tcp'
  "Open port  3401 for squid monitoring":
    ensure: present
    zone: public
    port: 3401
    protocol: 'udp'
