---
classes:
  - profile::firewalld
  - profile::xrootd::gateway
  - profile::cephfs

cvmfs::cvmfs_cache_base: '/var/cache/cvmfs'

site::site_info::cvmfs_mounts:
    grid.cern.ch:
      cvmfs_quota_limit: 1000

firewalld::custom_services:
  xrootd:
    short: 'xrootd'
    description: 'XRootD service on port 1094'
    ports:
      - port: 1094
        protocol: 'tcp'
    ipv4_destination: '127.0.0.1'
    ipv6_destination: '::1'
  "dice-api":
    short: 'dice-api'
    description: 'DICE API service on port 4935'
    ports:
      - port: 4935
        protocol: 'tcp'
    ipv4_destination: '127.0.0.1'
    ipv6_destination: '::1'


firewalld::services:
  "Allow access to XRootD service on port 1094":
    service: xrootd
    zone: public
    ensure: present
  "Allow access to DICE API on port 4935":
    service: "dice-api"
    zone: public
    ensure: present

# since services are not working:
firewalld::ports:
  "Open port 1094 for xrootd":
    ensure: present
    zone: public
    port: 1094
    protocol: 'tcp'
  "Open port 4935 for dice-api":
    ensure: present
    zone: public
    port: 4935
    protocol: 'tcp'

profile::cephfs::keys:
  - dice-user
  - xrootd

profile::cephfs::mounts:
  '/dice':
    device: dice-user@.dicefs=/dice
  '/xrootd':
    device: xrootd@.dicefs=/xrootd
