#!/bin/bash
export PATH=/cvmfs/oasis.opensciencegrid.org/mis/apptainer/current/bin:$PATH

if [ "$1" == "--version" ]
then
  apptainer --version
  exit 0
fi

# user might not be set (e.g. when not using getenv in job config)
USER=`whoami`


# try to figure out the HOME for the user - default to condor workdir
if [ -d "/users/$USER" ]
then
  HOME="/users/$USER"
elif [ -d "/usersc/$USER" ]
then
  HOME="/usersc/$USER"
else
  HOME="$TMPDIR"
fi

# make sure SINGULARITY_HOME is set to a correct value (e.g a folder owned by the user)
export USER
export HOME
export SINGULARITY_HOME=$HOME
export APPTAINER_HOME=$HOME
export HOSTNAME=`hostname -f`

# determine extra bind mounts
APPTAINER_BINDPATH=$(/etc/condor/get_bind_mounts)
export APPTAINER_BINDPATH
# echo "Using additional bind mounts: ${APPTAINER_BINDPATH}"

# echo "Executing apptainer $1 ${@:2}"
apptainer $1 ${@:2}
